buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Gradle 8.0 requires a compatible Android Gradle Plugin.
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
