plugins {
    id 'com.android.application'
}

android {
    namespace 'com.texttoimage.ai'
    compileSdk 34

    defaultConfig {
        applicationId 'com.texttoimage.ai'
        minSdk 21
        targetSdk 34
        versionCode 8
        versionName "12"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.unity3d.ads:unity-ads:4.12.0'
}
